"use client";
import { Courgette } from "next/font/google";
import "./globals.css";
import Header from "./-commerce/Header";
import Footer from "./-commerce/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CartContext } from "./_context/CartContext";
import { useState } from "react";

const inter = Courgette({ subsets: ["latin"], weight: "400" });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setcart] = useState([]);
  return (
    <ClerkProvider>
      <CartContext.Provider value={{ cart, setcart }}>
        <html lang="en">
          <body className={inter.className} style={{ background: "#111827" }}>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
